### ISSUE TITLE
这个启动错误如何解决？

### ISSUE THREAD

**Issue by cui8** [XgzK/QL_variable#24]
```
程序死亡开始执行
检测到系统是 arch 执行 fsbot.py
sh: you need to specify whom to kill
Traceback (most recent call last):
  File "/val/fsbot.py", line 6, in <module>
    from com.bot.information import Interact
  File "/val/com/bot/information.py", line 9, in <module>
    from ..ql.ql_timing import Timing
  File "/val/com/ql/__init__.py", line 1, in <module>
    from .ql import QL
  File "/val/com/ql/ql.py", line 6, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

使用的系统是arm64（armbian）。

**Comment by XgzK** [comment]
方法一删除重新拉
方法二进入容器
执行
pip install -i https://mirrors.aliyun.com/pypi/simple/ -r /val/requirements.txt
方法三进入容器执行 pip install requests
